### PR TITLE
Add YAML Developer tools

### PR DESCRIPTION
**Pull request by farmio**
Add YAML Developer tools

Not sure if this is the correct way to add an item, but I thought I'll give it a stab based on previous PRs.

### CODE REVIEW

**Comment by frenck** [comment]
Don't forget to add the matching frontend PR! (Or does the frontend already support it?)

**Comment by farmio** [comment]
🤔 looking at how this works, it seems this is already implemented, but under the name "Server Controls". This seems a little bit awkward. Should this be renamed?

https://github.com/home-assistant/frontend/blob/50f089fd4fb18319ec41722e526eb925a8651575/src/panels/my/ha-panel-my.ts#L41

**Comment by frenck** [comment]
I personally think I would mark the old one in this repo deprecated (so it hides from the UI) and make sure the new one works as well.

**Comment by frenck** [comment]
Because there hasn't been any activity on this PR for quite some time now, I've decided to close it for being stale.

Feel free to re-open this PR when you are ready to pick up work on it again 👍

../Frenck

**Pull request closed without merging**
