### PR TITLE
Lovelace badges

### PR DESCRIPTION
**Pull request by balloob**
Use UI instead of Lovelace. Don't use word "config".

https://deploy-preview-55--my-home-assistant.netlify.app/faq/#supported-pages

image

### CODE REVIEW

**Review by frenck — APPROVED** [review]

**Comment by bramkragten** [comment]
Meeehhh... I don't like that we now use different names for the same thing

**Comment by frenck** [comment]
😁 Naming is awesome!

**Comment by bramkragten** [comment]
image

Where possible, not possible here, so let's use config :D

**Comment by balloob** [comment]
I'm leaning to using Lovelace Config because Lovelace is what we name it everywhere else. We want the badge to make sense on its own, not based on the context.

**Comment by frenck** [comment]
> I'm leaning to using Lovelace Config because Lovelace is what we name it everywhere else.

We don't actually. I've removed most occurrences from the UI and the documentation CI will fail if you use `config` anywhere.

**Comment by bramkragten** [comment]
Not config, but UI vs Lovelace

**Comment by bramkragten** [comment]
So, close this? @frenck ?

**Comment by frenck** [comment]
Yeah, let stick with what we have now

**Pull request closed without merging**
